In progress, making final adjustments to styling in css and giving de…
SharjeelSIqbal/code-journal pull request #5
Opened 2021-07-13 19:29 UTC by SharjeelSIqbal

…tail to areas that have been overlooked.

2021-07-13 23:08 UTC, SharjeelSIqbal commented
![Kapture 2021-07-13 at 16 03 33](https://user-images.githubusercontent.com/50930123/125536193-9549e1f2-11cd-47a0-b025-0e4cfd249dc3.gif)
![image](https://user-images.githubusercontent.com/50930123/125536358-61b81dba-0461-4a8a-a625-6837dd4cbe96.png)
![Kapture 2021-07-13 at 16 08 06](https://user-images.githubusercontent.com/50930123/125536435-1b427b2d-51a3-424c-9ed8-606ef522bdd4.gif)

2021-07-13 23:10 UTC, SharjeelSIqbal commented
![Kapture 2021-07-13 at 16 10 29](https://user-images.githubusercontent.com/50930123/125536604-2ca2cee7-3c02-4653-ab8f-12c942d624fa.gif)

2021-07-13 23:29 UTC, codingcodymiller requested changes

2021-07-13 23:29 UTC, codingcodymiller commented on js/main.js
> +  data.nextEntryId += 1;
You did not add a `entryId` property to the new entry before incrementing this, please do so

2021-07-13 23:29 UTC, codingcodymiller commented on js/main.js
> +  $notes.value = '';
Instead of doing this, you should do `$submit.reset()`

2021-07-13 23:29 UTC, codingcodymiller commented on js/main.js
> +  event.preventDefault();
I generally prefer that `event.preventDefault()` is the first line of any function it needs to be a part of, for the sake of readability

2021-07-13 23:29 UTC, codingcodymiller commented on js/main.js
> +}
This should only be done before the page unloads, not after every time the form is submitted. Also, all `localStorage` code should be in `data.js`, not `main.js`

2021-07-13 23:29 UTC, codingcodymiller commented on js/main.js
> +  }
You should just resave the entire parsed object as the new value for `data`

2021-07-14 00:12 UTC, SharjeelSIqbal commented
<img width="665" alt="Screen Shot 2021-07-13 at 5 11 36 PM" src="https://user-images.githubusercontent.com/50930123/125540955-5e95bfd8-6c7f-4f0d-bbe4-d393a15bca07.png">

2021-07-14 00:45 UTC, codingcodymiller requested changes

2021-07-14 00:45 UTC, codingcodymiller commented on js/main.js
> +    entryId: data.entries.length
this should be `entryId: data.nextEntryId`

2021-07-14 00:45 UTC, codingcodymiller commented on js/main.js
> +  data.nextEntryId = data.entries.length;
This is wrong, you should just be incrementing the value by 1

2021-07-14 01:01 UTC, codingcodymiller approved these changes

2021-07-14 05:27 UTC, merged